name: 'RabbitMQ Message Sender'
description: 'Send a message to a queue on a RabbitMQ server'
branding:
  icon: 'message-square'
  color: 'green'
inputs:
  RABBIT_USERNAME:
    description: 'Rabbit Username'
    required: true
    default: 'guest'
  RABBIT_PASSWORD:
    description: 'Rabbit Password'
    required: true
    default: 'guest'
  RABBIT_HOST:
    description: 'Rabbit Hostname'
    required: true
    default: 'localhost'
  RABBIT_PORT:
    description: 'RabbitMQ Port'
    required: true
    default: '5672'
  RABBIT_USE_SSL:
    description: 'Use SSL'
    required: true
    default: 'true'
  RABBIT_QUEUE_NAME:
    description: 'Name for the queue'
    required: true
    default: 'rabbit-sender'
  MESSAGE:
    description: 'Message to be sent'
    required: true
    default: 'Hello World!'
  DURABLE:
    description: 'Durability for the queue'
    required: true
    default: 'true'
runs:
  using: 'docker'
  image: 'docker://quiquefe/rabbit-sender:latest'
  args:
    - ${{ inputs.RABBIT_USERNAME }}
    - ${{ inputs.RABBIT_PASSWORD }}
    - ${{ inputs.RABBIT_HOST }}
    - ${{ inputs.RABBIT_PORT }}
    - ${{ inputs.RABBIT_USE_SSL }}
    - ${{ inputs.RABBIT_QUEUE_NAME }}
    - ${{ inputs.MESSAGE }}
    - ${{ inputs.DURABLE }}
