name: 'RabbitMQ Message Sender'
description: 'Send a message to a queue on a RabbitMQ server'
branding:
  icon: 'message-square'
  color: 'green'
inputs:
  RABBIT_USERNAME:
    description: 'Rabbit Username'
    required: false
    default: 'rabbit'
  RABBIT_QUEUE_NAME:
    description: 'Name for the queue'
    required: false
  MESSAGE:
    description: 'Message to be sent'
    required: false
  RABBIT_PASSWORD:
    description: 'Rabbit Password'
    required: false
  RABBIT_HOST:
    description: 'Rabbit Hostname'
    required: false
  RABBIT_USE_SSL:
    description: 'Use SSL'
    required: false
  RABBIT_PORT:
    description: 'RabbitMQ Port'
    required: false
runs:
  using: 'docker'
  image: 'docker://quiquefe/rabbit-sender:latest'
  args:
    - ${{ inputs.RABBIT_HOST }}
    - ${{ inputs.RABBIT_USE_SSL }}
    - ${{ inputs.RABBIT_PASSWORD }}
    - ${{ inputs.RABBIT_USERNAME }}
    - ${{ inputs.RABBIT_QUEUE_NAME }}
    - ${{ inputs.RABBIT_PORT }}
    - ${{ inputs.MESSAGE }}
