name: build-n-push

on:
  push:
    tags:
      - '*'

jobs:

  build-n-push:

    name: build and push to docker hub
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: login to dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: quiquefe/${{ github.event.repository.name }}:latest

